config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'dashboard#index'
  resources :products
  resources :currencies
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  namespace :api do
    root 'products#index'
    resources :products
    resources :currencies do
      collection do
        post :upload
      end
    end
    post 'products/upload' => 'products#upload'
    get 'dashboard/stats' => 'dashboard#stats'
  end
end

app/models/currency.rb
# frozen_string_literal: true

class Currency < ApplicationRecord
  has_many :products
  validates :name, presence: true
  validates :currency_code, presence: true
  validates :name, uniqueness: true
  validates :currency_code, uniqueness: true
end

app/controllers/api/currencies_controller.rb
# frozen_string_literal: true

module Api
  class CurrenciesController < ApplicationController
    include Pagy::Backend
    protect_from_forgery with: :null_session
    before_action :set_currency, only: %i[show edit update destroy]

    # GET /currencies or /currencies.json
    def index
      @currencies = Currency.all
      render json: @currencies
    end

    # GET /currencies/1 or /currencies/1.json
    def show; end

    # GET /currencies/new
    def new
      @currency = Currency.new
    end

    # GET /currencies/1/edit
    def edit; end

    # POST /currencies or /currencies.json
    def create
      @currency = Currency.new(currency_params)

      respond_to do |format|
        if @currency.save
          format.json { render json: @currency, status: :created }
        else
          format.json { render json: @currency.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /currencies/1 or /currencies/1.json
    def update
      respond_to do |format|
        if @currency.update(currency_params)
          format.json { render json: @currency, status: :ok }
        else
          format.json { render json: @currency.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /currencies/1 or /currencies/1.json
    def destroy
      @currency.destroy

      respond_to do |format|
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_currency
      @currency = Currency.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def currency_params
      params.permit(:name, :currency_code)
    end
  end
end

app/controllers/currencies_controller.rb
# frozen_string_literal: true

class CurrenciesController < ApplicationController
  include Pagy::Backend
  before_action :set_currency, only: %i[show edit update destroy]

  # GET /currencies or /currencies.json
  def index
    @pagy, @currencies = pagy(Currency.all)
  end

  # GET /currencies/1 or /currencies/1.json
  def show; end

  # GET /currencies/new
  def new
    @currency = Currency.new
  end

  # GET /currencies/1/edit
  def edit; end

  # POST /currencies or /currencies.json
  def create
    @currency = Currency.new(currency_params)

    respond_to do |format|
      if @currency.save
        format.html { redirect_to currency_url(@currency), notice: 'Currency was successfully created.' }
        format.json { render :show, status: :created, location: @currency }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /currencies/1 or /currencies/1.json
  def update
    respond_to do |format|
      if @currency.update(currency_params)
        format.html { redirect_to currency_url(@currency), notice: 'Currency was successfully updated.' }
        format.json { render :show, status: :ok, location: @currency }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1 or /currencies/1.json
  def destroy
    @currency.destroy

    respond_to do |format|
      format.html { redirect_to currencies_url, notice: 'Currency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_currency
    @currency = Currency.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def currency_params
    params.require(:currency).permit(:name, :currency_code)
  end
end

app/helpers/currencies_helper.rb
# frozen_string_literal: true

module CurrenciesHelper
end

app/views/currencies/_currency.html.erb
<div id="<%= dom_id currency %>">
  <p>
    <strong>Name:</strong>
    <%= currency.name %>
  </p>

  <p>
    <strong>Currency code:</strong>
    <%= currency.currency_code %>
  </p>

</div>

app/views/currencies/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card p-5">
      <%= form_with model: @currency do |f| %>
        <% if @currency.errors.any? %>
          <div class="alert alert-danger">
            <ul>
              <% @currency.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, class: "form-control", placeholder: 'New item' %>
        </div>
        <div class="form-group">
          <%= f.label :currency_code, "Currency Code" %>
          <%= f.text_field :currency_code, class: "form-control", placeholder: 'XXX1' %>
        </div>
        <div class="form-group">
          <%= f.submit "Save", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/currencies/edit.html.erb
<h1>Editing currency</h1>

<%= render "form", currency: @currency %>

<br>

<div>
  <%= link_to "Show this currency", @currency %> |
  <%= link_to "Back to currencies", currencies_path %>
</div>

app/views/currencies/index.html.erb
<h1>Currency List</h1>
<a href="<%= new_currency_path %>" class="btn btn-primary btn-icon-split">
  <span class="icon text-white-50">
      <i class="fas fa-flag"></i>
  </span>
  <span class="text">Create Currency</span>
</a>
<a href="<%= currencies_path(format: :xlsx) %>" class="btn btn-success btn-icon-split">
  <span class="icon text-white-50">
      <i class="fas fa-file"></i>
  </span>
  <span class="text">Export to Excel</span>
</a>
<br><br>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Currency Code</th>
      <th>Actions</th>
  </thead>
  <tbody>
    <% @currencies.each do |currency| %>
    <tr>
      <td><%= currency.id %></td>
      <td><%= currency.name %></td>
      <td><%= currency.currency_code %></td>
      <td><%= link_to "Details", currency_path(currency), class: 'btn btn-primary' %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="d-flex justify-content-center">
<%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/currencies/new.html.erb
<h1>New currency</h1>

<%= render "form", currency: @currency %>

<br>

<div>
  <%= link_to "Back to currencies", currencies_path %>
</div>

app/views/currencies/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Currency Details</h1>
    <%= link_to "Back to currencies", currencies_path, class: 'btn btn-secondary' %>
    <%= link_to "Edit", edit_currency_path(@currency), class: 'btn btn-primary' %>
    <div class="card" style="padding: 20px;">
      <table class="table">
        <tr>
          <td><b>Currency Name:</b></td>
          <td><%= @currency.name %></td>
        </tr>
        <tr>
          <td><b>Currency Code:</b></td>
          <td><%= @currency.currency_code %></td>
        </tr>
          <td><b>Created at:</b></td>
          <td><%= @currency.created_at %></td>
        </tr>
        <tr>
          <td><b>Updated at:</b></td>
          <td><%= @currency.updated_at %></td>
        </tr>
      </table>
    </div>
  </div>
</div>
<br>