config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'dashboard#index'
  resources :products
  resources :currencies
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  namespace :api do
    root 'products#index'
    resources :products
    resources :currencies do
      collection do
        post :upload
      end
    end
    post 'products/upload' => 'products#upload'
    get 'dashboard/stats' => 'dashboard#stats'
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :currency
  validates :name, :price, :expiration, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates :name, uniqueness: true
  validates :name, format: { with: /.*#\(\d{16}\)/ }
end

app/controllers/api/products_controller.rb
# frozen_string_literal: true

module Api
  class ProductsController < ApplicationController
    include Pagy::Backend
    protect_from_forgery with: :null_session
    before_action :set_product, only: %i[show edit update destroy]
    before_action :upload_csv_params, only: [:upload]

    # POST /products/upload
    def upload
      csv = params[:csv]
      file_name = "/tmp/temp#{SecureRandom.hex(10)}.csv"
      CsvService::CleanCsv.clean_file(csv.path, file_name)
      CsvUploader::UploadWorker.perform_async(file_name)
      render json: { message: 'Products have been uploaded!' }, status: :ok
    end

    # GET /products or /products.json
    def index
      @products = Product.all

      render json: @products
    end

    # GET /products/1 or /products/1.json
    def show; end

    # GET /products/new
    def new
      @product = Product.new
    end

    # GET /products/1/edit
    def edit; end

    # POST /products or /products.json
    def create
      @product = Product.new(product_params)

      respond_to do |format|
        if @product.save

          format.json { render json: @product, status: :created }
        else

          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /products/1 or /products/1.json
    def update
      respond_to do |format|
        if @product.update(product_params)

          format.json { render json: @product, status: :ok }
        else

          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /products/1 or /products/1.json
    def destroy
      @product.destroy

      respond_to do |format|
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.permit(:name, :price, :expiration, :currency_id)
    end

    def upload_csv_params
      params.permit(:csv)
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  include Pagy::Backend
  before_action :set_product, only: %i[show edit update destroy]

  # GET /products or /products.json
  def index
    params[:items] ||= Pagy::DEFAULT[:items]
    params[:page] ||= Pagy::DEFAULT[:page]
    @pagy, @products = pagy(Product.all)
    respond_to do |format|
      format.html
      format.xlsx do
        response.headers['Content-Disposition'] = 'attachment; filename="ProductList.xlsx"'
      end
    end
  end

  # GET /products/1 or /products/1.json
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :price, :expiration, :currency_id)
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/products/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card p-5">
      <%= form_with model: @product do |f| %>
        <% if @product.errors.any? %>
          <div class="alert alert-danger">
            <ul>
              <% @product.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, class: "form-control", placeholder: 'New item' %>
        </div>
        <div class="form-group">
          <%= f.label :price, "Price" %>
          <%= f.text_field :price, class: "form-control", placeholder: '10.23' %>
        </div>
        <div class="form-group">
          <%= f.label :expiration, "Expiration" %>
          <%= f.date_field :expiration, class: "form-control", placeholder: 'Here goes the description...' %>
        </div>
        <div class="form-group">
          <%= f.label :currency_id, "Currency" %>
          <%= f.collection_select :currency_id, Currency.all, :id, :currency_code, prompt: true, class: "dropdown-menu" %>
        </div>
        <div class="form-group">
          <%= f.submit "Save", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Expiration:</strong>
    <%= product.expiration %>
  </p>

  <p>
    <strong>Currency:</strong>
    <%= product.currency_id %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<h1>Product List</h1>
<a href="<%= new_product_path %>" class="btn btn-primary btn-icon-split">
  <span class="icon text-white-50">
      <i class="fas fa-flag"></i>
  </span>
  <span class="text">Create Product</span>
</a>
<a href="<%= products_path(format: :xlsx) %>" class="btn btn-success btn-icon-split">
  <span class="icon text-white-50">
      <i class="fas fa-file"></i>
  </span>
  <span class="text">Export to Excel</span>
</a>
<br><br>
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Price</th>
      <th>Expiration</th>
      <th>Actions</th>
  </thead>
  <tbody>
    <% @products.each do |product| %>
    <tr>
      <td><%= product.id %></td>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
      <td><%= product.expiration %></td>
      <td><%= link_to "Details", product_path(product), class: 'btn btn-primary' %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="d-flex justify-content-center">
<%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Product Details</h1>
    <%= link_to "Back to products", products_path, class: 'btn btn-primary' %>
    <%= link_to "Edit", edit_product_path(@product), class: 'btn btn-primary' %>
    <div class="card" style="padding: 20px;">
      <table class="table">
        <tr>
          <td><b>Product Name:</b></td>
          <td><%= @product.name %></td>
        </tr>
        <tr>
          <td><b>Price:</b></td>
          <td><%= @product.price %></td>
        </tr>
        <tr>
          <td><b>Expiration:</b></td>
          <td><%= @product.expiration %></td>
        </tr>
        <tr>
          <td><b>Created at:</b></td>
          <td><%= @product.created_at %></td>
        </tr>
        <tr>
          <td><b>Updated at:</b></td>
          <td><%= @product.updated_at %></td>
        </tr>
      </table>
    </div>
  </div>
</div>
<br>